# Generated by Django 3.1 on 2020-08-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='lte_exist',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.TextField(),
        ),
    ]
