# Generated by Django 3.1 on 2020-08-23 19:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20200823_2019'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='phone',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
