# Generated by Django 3.1 on 2020-08-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20200823_2223'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='phone',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
